trigger:
- main

variables:
- group: Variables

pool:
  vmImage: ubuntu-latest

stages:
- stage: Planning
  displayName: Deployment planning

  jobs: 
    - job: Planning
      steps:
      - task: AzureCLI@2
        displayName: Terraform init
        inputs:
          azureSubscription: 'AzureCloud'
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: 'terraform init -backend-config="resource_group_name=Services" -backend-config="storage_account_name=intvservicestorageacc" -backend-config="container_name=terraform" -backend-config="key=sbx.tfstate" -backend-config="access_key=$(access_key)"'
      - task: AzureCLI@2
        displayName: Terraform plan
        inputs:
          azureSubscription: 'AzureCloud'
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: 'terraform plan -var="company=intvsn" -var="client=lab" -var="environment=sbx" -var="location=westeurope" -var="aks_cluster_name=wordpress" -out="sbx.tfplan"'

- stage: Applying
  displayName: Deployment applying

  jobs:
    - deployment: publishinternal
      displayName: 'Approval'
      environment: $(environmentName)

    - job: Applying
      steps:
      - task: AzureCLI@2
        displayName: Terraform apply
        inputs:
          azureSubscription: 'AzureCloud'
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: 'terraform apply "sbx.tfplan"'