trigger:
- main

variables:
- group: VisualStudio

pool:
  vmImage: ubuntu-latest

steps:

- task: AzureCLI@2
  inputs:
    azureSubscription: 'VisualStudio'
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: 'terraform version'