trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformTaskV1@0
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'VisualStudio'
    backendAzureRmResourceGroupName: 'Services'
    backendAzureRmStorageAccountName: 'intvservicestorageacc'
    backendAzureRmContainerName: 'terraform'
    backendAzureRmKey: 'sbx'

- task: TerraformTaskV1@0
  inputs:
    provider: 'azurerm'
    command: 'plan'
    commandOptions: '-var="company=intvsn" -var="client=lab" -var="environment=sbx" -var="location=westeurope" -var="aks_cluster_name=wordpress"'
    environmentServiceNameAzureRM: 'VisualStudio'